# Generated by Django 4.2.5 on 2023-10-02 07:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('recipe', models.TextField(max_length=2000, verbose_name='рецепт')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'завтрак'), ('LUNCH', 'обед'), ('DINNER', 'ужин'), ('DESSERT', 'десерт')], max_length=20, verbose_name='тип приема пищи')),
                ('allergens', models.CharField(choices=[('FISH', 'рыба и морепродукты'), ('MEAT', 'мясо'), ('CEREAL', 'зерновые'), ('HONEY', 'продукты пчеловодства'), ('NUTS', 'орехи и бобовые'), ('MILK', 'молочные продукты')], max_length=10, verbose_name='аллергены')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
    ]
