# Generated by Django 4.2.5 on 2023-10-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('period', models.CharField(choices=[('1', '1 месяц'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '12 месяцев')], default='1', max_length=10, verbose_name='Период')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала')),
                ('ends_at', models.DateTimeField(verbose_name='дата окончания')),
                ('meal_types', multiselectfield.db.fields.MultiSelectField(choices=[('BREAKFAST', 'завтрак'), ('LUNCH', 'обед'), ('DINNER', 'ужин'), ('DESSERT', 'десерт')], max_length=50, verbose_name='тип приема пищи')),
                ('allergy_types', multiselectfield.db.fields.MultiSelectField(choices=[('FISH', 'рыба и морепродукты'), ('MEAT', 'мясо'), ('CEREAL', 'зерновые'), ('HONEY', 'продукты пчеловодства'), ('NUTS', 'орехи и бобовые'), ('MILK', 'молочные продукты')], max_length=50, verbose_name='аллергены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
